In [2]:
import numpy as np

## 예시. 다음 Instrunction에 해당하는 transtition matrix를 찾으시오.

1. V0 <- V0
2. V1 <- V1+1
3. IF V1 $\neq$ 0 GOTO 5
4. V0 <- V0-1
5. END (Do Nothing)
<br>


- variable의 수: 2
- branch instruction의 수: 1
- branch instruction의 경우 한 개당 두개의 추가 instrunction이 필요함.
- operation의 수: 5
- transition matrix의 사이즈: 9X9 $\because$(2+2*1+5)=9

In [3]:
MAT = np.array([[1,0,0,0,0,0,0,0,0],
                 [0,1,0,0,0,0,0,0,-1],
                 [0,0,0,1,0,0,0,0,0],
                 [0,1,0,0,1,0,0,0,0],
                 [0,0,0,0,0,0,0,1,1],
                 [-1,0,0,0,0,0,1,0,0],
                 [0,0,0,0,0,0,0,0,0],
                 [0,0,0,0,0,0,1,0,0],
                 [0,0,0,0,0,1,-1,0,0],
                ])

In [4]:
INIT = np.array([1,2,1,0,0,0,0,0,0])

curr = INIT
for _ in range(10):
    curr = np.matmul(curr, MAT)
    curr = curr.clip(min=0)
    print(curr)

[1 2 0 1 0 0 0 0 0]
[1 3 0 0 1 0 0 0 0]
[1 3 0 0 0 0 0 1 0]
[1 3 0 0 0 0 1 0 0]
[1 3 0 0 0 0 0 0 0]
[1 3 0 0 0 0 0 0 0]
[1 3 0 0 0 0 0 0 0]
[1 3 0 0 0 0 0 0 0]
[1 3 0 0 0 0 0 0 0]
[1 3 0 0 0 0 0 0 0]
