In [104]:
import numpy as np

#There is 2 states and 7+2 instructions
initial_state = np.array([1, 2])
initial_instruction = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0])

initial = np.concatenate([initial_state, initial_instruction])

In [105]:
def transition_mat(vec):
    transition = np.array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                           [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, -1],
                           [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
                           [0, -1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
                           [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                           [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
                           [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
                           [0, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
                           [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                           [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
                           [0, 0, 0, 0, 0, 0, 1, -1, 0, 0, 0]])
    
    return np.matmul(vec, transition)

In [106]:
curr = initial
for _ in range(10):
    curr = transition_mat(curr)
    curr = curr.clip(min=0)
    print(curr)

[1 2 0 1 0 0 0 0 0 0 0]
[1 1 0 0 1 0 0 0 0 0 0]
[2 1 0 0 0 1 0 0 0 0 0]
[2 1 0 0 0 0 0 0 0 1 0]
[2 1 0 0 0 0 0 1 0 0 0]
[2 0 0 0 0 0 0 0 1 0 0]
[2 0 0 0 0 0 0 0 0 0 0]
[2 0 0 0 0 0 0 0 0 0 0]
[2 0 0 0 0 0 0 0 0 0 0]
[2 0 0 0 0 0 0 0 0 0 0]
